//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1873
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WZ.Web {
    
    
    public partial class _Default1 {
        
        /// <summary>
        /// stst 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.ShowText stst;
        
        /// <summary>
        /// ucTop 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Web.ascx.top ucTop;
        
        /// <summary>
        /// ProClassIndex1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Web.ascx.Pro_ClassIndex ProClassIndex1;
        
        /// <summary>
        /// wAdv1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdv1;
        
        /// <summary>
        /// rpPPT 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.Templated.Rep rpPPT;
        
        /// <summary>
        /// rpRecommend 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Pro_ListPic rpRecommend;
        
        /// <summary>
        /// rpWebNotice 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.Templated.Rep rpWebNotice;
        
        /// <summary>
        /// rpWebActive 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.Templated.Rep rpWebActive;
        
        /// <summary>
        /// wAdv2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdv2;
        
        /// <summary>
        /// rpHot 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Pro_ListPic rpHot;
        
        /// <summary>
        /// wAdv6 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdv6;
        
        /// <summary>
        /// rpClass1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.Templated.Rep rpClass1;
        
        /// <summary>
        /// wAdvLeft1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdvLeft1;
        
        /// <summary>
        /// rpClassPro1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Pro_ListPic rpClassPro1;
        
        /// <summary>
        /// Help_Info1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info Help_Info1;
        
        /// <summary>
        /// wAdv3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdv3;
        
        /// <summary>
        /// rpClass2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.Templated.Rep rpClass2;
        
        /// <summary>
        /// wAdvLeft2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdvLeft2;
        
        /// <summary>
        /// rpClassPro2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Pro_ListPic rpClassPro2;
        
        /// <summary>
        /// Help_Info2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info Help_Info2;
        
        /// <summary>
        /// wAdv4 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdv4;
        
        /// <summary>
        /// rpClass3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Common.Control.Templated.Rep rpClass3;
        
        /// <summary>
        /// wAdvLeft3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdvLeft3;
        
        /// <summary>
        /// rpClassPro3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Pro_ListPic rpClassPro3;
        
        /// <summary>
        /// Help_Info3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info Help_Info3;
        
        /// <summary>
        /// wAdv5 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Adv_Info wAdv5;
        
        /// <summary>
        /// wHelp 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info wHelp;
        
        /// <summary>
        /// wHelp1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info wHelp1;
        
        /// <summary>
        /// wHelp2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info wHelp2;
        
        /// <summary>
        /// wHelp3 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info wHelp3;
        
        /// <summary>
        /// wHelp4 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Client.Control.Help_Info wHelp4;
        
        /// <summary>
        /// ucLinks1 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Web.ascx.links ucLinks1;
        
        /// <summary>
        /// ucLinks2 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Web.ascx.links ucLinks2;
        
        /// <summary>
        /// ucBottom 控件。
        /// </summary>
        /// <remarks>
        /// 自动生成的字段。
        /// 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        /// </remarks>
        protected global::WZ.Web.ascx.bottom ucBottom;
    }
}
